services:
  - type: web
    name: churn-api
    env: python
    pythonVersion: 3.10.13
    plan: free
    rootDir: churn-api
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true

