services:
  - type: web
    name: churn-api
    env: python
    plan: free
    rootDir: churn-api
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true